[@ww.textfield labelKey="Download Katalon Version" name="version" required='false' cssClass='long-field' /]
[@ww.textfield labelKey="Use pre-installed Katalon Studio" name="location" required='false' cssClass='long-field'/]
[@ww.textarea labelKey="Command arguments" name="executeArgs" required='false' rows='5' cssClass='long-field' /]
[@ww.textfield labelKey="X11 DISPLAY (for Linux)" name="x11Display" required='false'cssClass='long-field' /]
[@ww.textfield labelKey="Xvfb-run configuration" name="xvfbConfiguration" required='false' cssClass='long-field' /]